#! /usr/bin/env bash

set -euo pipefail

rm -rf output/test
python main.py --workdir output/test --config configs/subvp/xarray_cunet_continuous.py --mode train --config.data.dataset_name=2.2km-coarsened-8x_london_vorticity850_random-sample --config.training.snapshot_freq=5 --config.training.eval_freq=2 --config.training.log_freq=1 --config.training.n_iters=15
